/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tiantian_ndkdemo_MainActivity */

#ifndef _Included_tiantian_ndkdemo_MainActivity
#define _Included_tiantian_ndkdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tiantian_ndkdemo_MainActivity
 * Method:    getstringfromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tiantian_ndkdemo_MainActivity_getstringfromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
